numero = 0 

resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1
resultado = numero * 7
print(numero, "x 7 =", resultado)
numero += 1

